[project]
name = "harasho-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "mcp>=1.22.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
